### ISSUE TITLE
Use of docker meta action for version

### ISSUE THREAD

**Issue by kurmann** [kurmann/Videoschnitt.Engine#86]
```yaml
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

```
